### ISSUE TITLE
Scape { in regex

### ISSUE THREAD

**Issue by cibersheep** [8bat/the_inker#1]
I know there's been a long time from this :) but I'm testing [galaxias](https://ifdb.org/viewgame?id=zl8pbm6e1oz6pe2f)
```
$ ./script/the_translator.pl --out=galaxia-ngpaws galaxia.txt 
Unescaped left brace in regex is passed through in regex; marked by <-- HERE in m/^static char udg_bits\[\] = { <-- HERE $/ at lib/TheScribe.pm line 592.
Unescaped left brace in regex is passed through in regex; marked by <-- HERE in m/^static char font(\d+)_bits\[\] = { <-- HERE $/ at lib/TheScribe.pm line 607.
```

**Comment by andrew-sayers** [comment]
Long time no see :)

The good news is that this and #2 are fairly easy to fix, and the program produces some output with those fixes - I'll push something out in a moment.

The bad news is that the output is pretty rough, several files have serious errors, and I'm unlikely to have much time to dig into them in the near future.  I seem to remember the output always needed to be tweaked manually, so at least this might give you a basis to start from.

**Comment by andrew-sayers** [comment]
Oh, and for the record hi - I'm the same developer behind the "8bat" account.  That account should probably always have been an organisation, I just didn't know how to do that when I created it :)

**Comment by cibersheep** [comment]
Hello hello hello :)
First, thanks to take the time to look into it and second, I might sit down and check better the code (that might help ^__^)
I'll see what I can do.
